-- I3-03B: apply after 001 to the same isolated database. Never to a live DB automatically.
-- Catalog contains only references/hashes, not source or participant PII.
BEGIN;
CREATE ROLE rc_admission NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
SET LOCAL ROLE rc_control_owner;

CREATE TABLE rc_control.approved_versions (
  owner_id uuid NOT NULL,
  scope_id text NOT NULL CHECK(scope_id ~ '^[a-z][a-z0-9-]{0,31}$'),
  version_id text NOT NULL CHECK(version_id ~ '^[A-Za-z0-9_-]{1,64}$'),
  source_sha256 text NOT NULL CHECK(source_sha256 ~ '^[0-9a-f]{64}$'),
  program_sha256 text NOT NULL CHECK(program_sha256 ~ '^[0-9a-f]{64}$'),
  java_sha256 text NOT NULL CHECK(java_sha256 ~ '^[0-9a-f]{64}$'),
  active boolean NOT NULL DEFAULT false,
  revision bigint NOT NULL DEFAULT 1 CHECK(revision > 0),
  PRIMARY KEY(owner_id,scope_id,version_id)
);
ALTER TABLE rc_control.approved_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE rc_control.approved_versions FORCE ROW LEVEL SECURITY;
CREATE POLICY owner_only ON rc_control.approved_versions TO rc_control_owner USING(true) WITH CHECK(true);

CREATE FUNCTION rc_control.preserve_version() RETURNS trigger LANGUAGE plpgsql
SET search_path=pg_catalog AS $$
BEGIN
  IF ROW(NEW.owner_id,NEW.scope_id,NEW.version_id,NEW.source_sha256,NEW.program_sha256,NEW.java_sha256)
      IS DISTINCT FROM
      ROW(OLD.owner_id,OLD.scope_id,OLD.version_id,OLD.source_sha256,OLD.program_sha256,OLD.java_sha256) THEN
    RAISE EXCEPTION 'VERSION_IMMUTABLE';
  END IF;
  -- Revision is generated by the DB even when an administrator reactivates a leaf.
  NEW.revision := OLD.revision + 1;
  RETURN NEW;
END $$;
CREATE TRIGGER immutable_version BEFORE UPDATE ON rc_control.approved_versions
FOR EACH ROW EXECUTE FUNCTION rc_control.preserve_version();

CREATE FUNCTION rc_control.admission_snapshot(p_owner uuid,p_scope text,p_version text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE cfg rc_control.settings; v rc_control.approved_versions;
BEGIN
  SELECT * INTO STRICT cfg FROM rc_control.settings WHERE singleton FOR SHARE;
  IF NOT cfg.enabled THEN RAISE EXCEPTION 'EXECUTION_DISABLED'; END IF;
  SELECT * INTO v FROM rc_control.approved_versions
    WHERE owner_id=p_owner AND scope_id=p_scope AND version_id=p_version AND active FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'VERSION_UNAUTHORIZED'; END IF;
  RETURN jsonb_build_object('source_sha256',v.source_sha256,'program_sha256',v.program_sha256,
    'java_sha256',v.java_sha256,'revision',v.revision,'policy_sha256',cfg.policy_sha256);
END $$;

CREATE FUNCTION rc_control.enqueue_admitted(p_owner uuid,p_scope text,p_key text,
                                            p_descriptor jsonb,p_revision bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE cfg rc_control.settings; v rc_control.approved_versions; old_deadline timestamptz;
BEGIN
  -- Lock order is settings -> version -> job; no compilation while holding locks.
  SELECT * INTO STRICT cfg FROM rc_control.settings WHERE singleton FOR UPDATE;
  IF NOT cfg.enabled THEN RAISE EXCEPTION 'EXECUTION_DISABLED'; END IF;
  IF jsonb_typeof(p_descriptor) IS DISTINCT FROM 'object'
     OR octet_length(p_descriptor::text)>4096 THEN RAISE EXCEPTION 'DESCRIPTOR_INVALID'; END IF;
  SELECT * INTO v FROM rc_control.approved_versions WHERE owner_id=p_owner AND scope_id=p_scope
    AND version_id=p_descriptor->>'version_id' AND active FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'VERSION_UNAUTHORIZED'; END IF;
  IF p_revision IS DISTINCT FROM v.revision THEN RAISE EXCEPTION 'VERSION_CHANGED'; END IF;
  IF p_descriptor->>'source_sha256' IS DISTINCT FROM v.source_sha256
     OR p_descriptor->>'program_sha256' IS DISTINCT FROM v.program_sha256
     OR p_descriptor->>'java_sha256' IS DISTINCT FROM v.java_sha256 THEN
    RAISE EXCEPTION 'VERSION_MISMATCH';
  END IF;
  IF p_descriptor->>'policy_sha256' IS DISTINCT FROM cfg.policy_sha256 THEN
    RAISE EXCEPTION 'POLICY_MISMATCH';
  END IF;
  SELECT deadline_at INTO old_deadline FROM rc_control.jobs
    WHERE owner_id=p_owner AND idempotency_key=p_key;
  -- Identical retry must not extend the original deadline or create a new job.
  RETURN rc_control.enqueue(p_owner,p_scope,p_key,p_descriptor,
    coalesce(old_deadline,clock_timestamp()+interval '240 seconds'));
END $$;

REVOKE ALL ON rc_control.approved_versions FROM PUBLIC,rc_broker,rc_admission;
REVOKE ALL ON FUNCTION rc_control.preserve_version(),
  rc_control.admission_snapshot(uuid,text,text),
  rc_control.enqueue_admitted(uuid,text,text,jsonb,bigint) FROM PUBLIC,rc_broker,rc_admission;
-- Close the old unverified descriptor entrypoint for the execution role.
REVOKE EXECUTE ON FUNCTION rc_control.enqueue(uuid,text,text,jsonb,timestamptz) FROM rc_broker;
GRANT USAGE ON SCHEMA rc_control TO rc_admission;
GRANT EXECUTE ON FUNCTION rc_control.admission_snapshot(uuid,text,text),
  rc_control.enqueue_admitted(uuid,text,text,jsonb,bigint) TO rc_admission;
COMMIT;
